# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentDeck < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/asheshgoplani/agent-deck"
  version "0.8.95"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v0.8.95/agent-deck_0.8.95_darwin_amd64.tar.gz"
      sha256 "8d48a8dcfde9caf98cc9f0267fa29321a2a2177ac1b927ef14f5d85b9f53fec2"

      def install
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v0.8.95/agent-deck_0.8.95_darwin_arm64.tar.gz"
      sha256 "09f8d5e5ce7803c029bdb759e102acd7ab4df9c0e0c3ee629cb85a791af16428"

      def install
        bin.install "agent-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v0.8.95/agent-deck_0.8.95_linux_amd64.tar.gz"
      sha256 "daf37745f9954ea38396ba73046687b32c249b69067765144d0b9b3ddff7a560"
      def install
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v0.8.95/agent-deck_0.8.95_linux_arm64.tar.gz"
      sha256 "3ea9afca8543517b56dbc0a391fd1cb7333684ba153e2de0d3fe7f668ac0963a"
      def install
        bin.install "agent-deck"
      end
    end
  end

  test do
    system "#{bin}/agent-deck", "version"
  end
end
