# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentDeck < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/asheshgoplani/agent-deck"
  version "1.9.73"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v1.9.73/agent-deck_1.9.73_darwin_amd64.tar.gz"
      sha256 "b627dd734cf8e391a27e178c1511a674ad89bb03b7989c1aca5fd4133bba1bac"

      define_method(:install) do
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v1.9.73/agent-deck_1.9.73_darwin_arm64.tar.gz"
      sha256 "797b969c50c4ad265c21c0732cb66833ecd5fb3594a68da54a6faf80be29a841"

      define_method(:install) do
        bin.install "agent-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v1.9.73/agent-deck_1.9.73_linux_amd64.tar.gz"
      sha256 "f314462540af7578e920d36da7716a0055256abb62197d96b2532c8ecf6096ba"
      define_method(:install) do
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asheshgoplani/agent-deck/releases/download/v1.9.73/agent-deck_1.9.73_linux_arm64.tar.gz"
      sha256 "0b0d5f63e993b5a44508b01cba19b877225ea14a8605b3b4f6702d84710b857c"
      define_method(:install) do
        bin.install "agent-deck"
      end
    end
  end

  test do
    system "#{bin}/agent-deck", "version"
  end
end
